# Generated by Django 5.2.6 on 2025-09-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_created_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=50)),
                ("customer_surname", models.CharField(max_length=50)),
                ("customer_patronym", models.CharField(max_length=100)),
                ("customer_address", models.TextField()),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                ("goods_id", models.AutoField(primary_key=True, serialize=False)),
                ("goods_name", models.CharField(max_length=255)),
                ("goods_descr", models.TextField()),
                ("goods_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("goods_img", models.ImageField(upload_to="products/")),
            ],
        ),
        migrations.CreateModel(
            name="Goods_category",
            fields=[
                (
                    "goods_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("category_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "order_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("status_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_cnt", models.IntegerField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.customers",
                    ),
                ),
                (
                    "goods_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.goods"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goods",
            name="goods_category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.goods_category"
            ),
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateTimeField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.customers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_cnt", models.IntegerField()),
                (
                    "goods_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.goods"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.orders"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdate", models.DateTimeField()),
                ("edate", models.DateTimeField()),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.orders"
                    ),
                ),
                (
                    "order_status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.status"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warehouse_id", models.IntegerField()),
                ("goods_cnt", models.IntegerField()),
                (
                    "goods_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.goods"
                    ),
                ),
            ],
        ),
    ]
