# Generated by Django 5.2.6 on 2025-09-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_created_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("brand_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="goods",
            name="brand_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="users.brand"
            ),
            preserve_default=False,
        ),
    ]
