# Generated by Django 5.2.6 on 2025-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_brand_goods_brand_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="goods_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
