# Generated by Django 5.2.6 on 2025-09-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_goods_goods_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="goods_cnt",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="goods",
            name="goods_img",
            field=models.ImageField(upload_to="goods/"),
        ),
    ]
