# Generated by Django 5.2.6 on 2025-09-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_cart_goods_cnt_alter_goods_goods_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="customer_password",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
