# Generated by Django 5.2.6 on 2025-09-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customers_customer_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="customer_phone",
            field=models.CharField(max_length=15),
        ),
    ]
